name:                containers-good-graph
version:             0.6.4.1
github:              "isovector/containers-good-graph"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "Data.Graph, but it doesn't suck!"
category:            Data Structures

description:         Please see the README on GitHub at <https://github.com/isovector/containers-good-graph#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- deepseq

library:
  source-dirs: src

tests:
  containers-good-graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers-good-graph
